'use client'
import '../globals.css'
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '../reduxProvider/Providers'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import { usePathname } from 'next/navigation'



const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'NextCommerce',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const dispatch = useAppDispatch()
  const pathname = usePathname()
  let isLogin = pathname.startsWith('/login')
  let isSignup = pathname.startsWith('/signup')
 


  return (
    <html lang="en">
      <body className={inter.className}>


        <Providers >
          {(!isLogin && !isSignup) && <Navbar />}

          {children}

          {(!isLogin && !isSignup) && <Footer />}
        </Providers>



      </body>
    </html>

  )
}
